### ISSUE TITLE
Will microbedb v2 hold locally created genomes, or only NCBI?

### ISSUE THREAD

**Issue by cometsong** [lairdm/microbedb#1]
in v1 of MicrobeDB, it can be extended to hold other file types, other info, etc. 

Can that also be done with this v2, or is this only to mirror the full NCBI genome db?

**Comment by lairdm** [comment]
That wasn't a functionality I needed where we used MicrobeDB (in Islandviewer where the original MDB was developed for), so I didn't recreate that functionality when updating it. I imagine it could be extended to have such functionality, but it's definitely not something I'll be looking in to, as I've moved positions and no longer actively maintain any of these tools. If you find a way I'd take pull requests, but sorry I can't give you a happier answer than that.

**Comment by cometsong** [comment]
Thanks @lairdm.
I'll check into porting it from v1 or recreating it for us.
